apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-deploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cm
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: cm
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: cm-demo
            items:
              - key: redis.conf
                path: path/to/msyql.conf
      containers:
        - name: testcm
          image: busybox
          command: [ "/bin/sh","-c","cat /etc/config/path/to/msyql.conf" ]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
        