apiVersion: v1
kind: Pod
metadata:
  name: resource-demo
spec:
  containers:
    - name: resource-demo
      image: nginx
      resources:
        limits:
          cpu: 100m
          memory: 500Mi
        requests:
          cpu: 50m
          memory: 300Mi
