apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      node: local
  template:
    metadata:
      labels:
        app: nginx
        node: local
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
